# Slack MCP Server with Supergateway - fly.toml
app = "slack-mcp-server"
primary_region = "nrt"  # Tokyo region

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # SSE 엔드포인트에 대한 특별 설정
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

# 환경변수 (민감하지 않은 것들만)
[env]
  NODE_ENV = "production"
  PORT = "8000"
  
# Slack API 관련 민감한 환경변수는 secrets로 설정
# flyctl secrets set SLACK_BOT_TOKEN=xoxb-your-token
# flyctl secrets set SLACK_USER_TOKEN=xoxp-your-token
# flyctl secrets set SLACK_TEAM_ID=your-team-id

[[mounts]]
  # 로그나 임시 파일용 (선택사항)
  destination = "/app/logs"
  source = "slack_mcp_logs"